# Generated by Django 5.2 on 2025-05-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
